### PR TITLE
Update hi.md

### PR DESCRIPTION
**Pull request by gosoccerboy5**
hi

I fixed the appearance of the hi.md file

(totally not desperate for a way to keep in touch with you???)

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
oops I guess I can also comment on infohub, but i decided to also help a bit by fixing hi.md

**Comment by dylanbmcc** [comment]
Yeah sorry I don’t really keep in touch, as I’m in Turkey at the moment

**Comment by gosoccerboy5** [comment]
> Yeah sorry I don’t really keep in touch, as I’m in Turkey at the moment

Oof. Well, you can always message me on github or scratch when you feel like

**Comment by gosoccerboy5** [comment]
How should I contact you in the future? InfoHub?

**Pull request merged**
